Update backward support oldest node v0.0.10, v0.0.12 for spread version
Update backward commit to support oldest node v0.0.10, v0.0.12 - [checking tests - build failing]

1. Managing minor changes to arguments passing to remove spread operator which is not supported by oldest node version 0.0.10.
2. Minor changes to afterCallback invocation. Inverting falsy check to a truthy check invocation for undefined checks for `res.send(body)` usage.
3. Using flatten function to flatten arguments passed.
4. Renaming afterCallback to afterSend
5. Test for `1) app.router:  should be .use()able: Error: expected 200 "OK", got 500 "Internal Server Error"` is expected to fail for res.send(body, afterSend). Do you need me to write tests for the same or the team will review the tests cases considering other tests?

`1) app.router:  should be .use()able: Error: expected 200 "OK", got 500 "Internal Server Error"`

```
Error: expected 200 "OK", got 500 "Internal Server Error"
      at Context.<anonymous> (test/app.router.js:161:6)
      at processImmediate (node:internal/timers:464:21)
```